services:
  redis_claude_job_soccer:
    image: redis:7
    container_name: redis_claude_job_soccer_dev
    ports:
      - "6381:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  # ================== MONGODB 3-NODE REPLICA SET ==================
  mongodb_primary:
    image: mongo:7
    container_name: mongodb_primary_dev
    ports:
      - "27017:27017"
    restart: always
    entrypoint: ["/mongo-entrypoint.sh"]
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile", "--quiet"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=claude_job_soccer_dev
    volumes:
      - mongodb_primary_data:/data/db
      - ./mongo-keyfile:/data/mongodb-keyfile
      - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  mongodb_secondary1:
    image: mongo:7
    container_name: mongodb_secondary1_dev
    ports:
      - "27018:27017"
    restart: always
    entrypoint: ["/mongo-entrypoint.sh"]
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile", "--quiet"]
    volumes:
      - mongodb_secondary1_data:/data/db
      - ./mongo-keyfile:/data/mongodb-keyfile
      - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
    depends_on:
      mongodb_primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  mongodb_secondary2:
    image: mongo:7
    container_name: mongodb_secondary2_dev
    ports:
      - "27019:27017"
    restart: always
    entrypoint: ["/mongo-entrypoint.sh"]
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile", "--quiet"]
    volumes:
      - mongodb_secondary2_data:/data/db
      - ./mongo-keyfile:/data/mongodb-keyfile
      - ./mongo-entrypoint.sh:/mongo-entrypoint.sh:ro
    depends_on:
      mongodb_primary:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  mongodb_setup:
    image: mongo:7
    container_name: mongodb_setup_dev
    depends_on:
      mongodb_primary:
        condition: service_healthy
      mongodb_secondary1:
        condition: service_healthy
      mongodb_secondary2:
        condition: service_healthy
    command: >
      mongosh --host mongodb_primary:27017 -u admin -p admin123 --authenticationDatabase admin --eval "
      try {
        const status = rs.status();
        print('Replica set already initialized: ' + status.set);
      } catch(err) {
        print('Initializing 3-node replica set...');
        rs.initiate({
          _id: 'rs0',
          members: [
            { _id: 0, host: 'mongodb_primary:27017', priority: 2 },
            { _id: 1, host: 'mongodb_secondary1:27017', priority: 1 },
            { _id: 2, host: 'mongodb_secondary2:27017', priority: 1 }
          ]
        });
        print('Replica set initialized successfully!');
        print('Primary: mongodb_primary:27017');
        print('Secondary1: mongodb_secondary1:27017');
        print('Secondary2: mongodb_secondary2:27017');
      }"
    restart: "no"
  claude_job_soccer-backend:
    build:
      context: ./claude_job_soccer_backend
      dockerfile: Dockerfile.dev
    container_name: claude_job_soccer-backend_dev
    ports:
      - "5013:5013"
    env_file:
      - ./claude_job_soccer_backend/.env.development
    volumes:
      - ./claude_job_soccer_backend:/app
      - node_modules:/app/node_modules    
      - ./logs:/logs
    depends_on:
      redis_claude_job_soccer:
        condition: service_healthy
      mongodb_primary:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_URL=mongodb://admin:admin123@mongodb_primary:27017,mongodb_secondary1:27017,mongodb_secondary2:27017/claude_job_soccer_dev?authSource=admin&replicaSet=rs0

  # Elasticsearch service
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch_claude_job_soccer_dev
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data_dev:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Kibana Service
  kibana:
    image: kibana:7.9.2
    container_name: kibana_claude_job_soccer_dev
    restart: always
    depends_on: 
      - elasticsearch 
    ports: 
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200" 


volumes:
  node_modules:
  elasticsearch_data_dev:
  mongodb_primary_data:
  mongodb_secondary1_data:
  mongodb_secondary2_data:
